export const RECIPES = [
  {id:'tortilla',name:'Tortilla de papa',emoji:'🥔',time:'30 min',description:'Un clásico rendidor para almorzar o cenar.',ingredients:['papa','huevo','cebolla'],steps:['Cortá y cociná las papas con la cebolla.','Batí los huevos, mezclá todo y condimentá.','Cociná en sartén de ambos lados hasta dorar.']},
  {id:'arroz',name:'Arroz salteado',emoji:'🍚',time:'20 min',description:'Ideal para aprovechar verduras que quedaron.',ingredients:['arroz','zanahoria','cebolla'],steps:['Cociná el arroz.','Salteá la cebolla y la zanahoria.','Sumá el arroz y mezclá con condimentos.']},
  {id:'fideos',name:'Fideos con salsa',emoji:'🍝',time:'25 min',description:'Una comida fácil con ingredientes de almacén.',ingredients:['fideos','tomate','cebolla'],steps:['Cociná los fideos en agua hirviendo.','Salteá cebolla y tomate para hacer la salsa.','Mezclá y serví.']},
  {id:'omelette',name:'Omelette de queso',emoji:'🍳',time:'12 min',description:'Rápido y rico para cualquier momento.',ingredients:['huevo','queso'],steps:['Batí los huevos con sal.','Volcá en sartén caliente y agregá queso.','Doblá al medio y cociná hasta que se derrita.']},
  {id:'ensalada',name:'Ensalada fresca',emoji:'🥗',time:'10 min',description:'Algo liviano y fresco con lo que haya.',ingredients:['lechuga','tomate','zanahoria'],steps:['Lavá bien las verduras.','Cortá todo en trozos.','Mezclá y condimentá a gusto.']},
  {id:'pizza',name:'Pizza casera',emoji:'🍕',time:'50 min',description:'Para compartir y usar lo que tenés.',ingredients:['harina','tomate','queso'],steps:['Prepará una masa con harina, agua y sal.','Estirá, agregá tomate y queso.','Horneá hasta que la base esté dorada.']},
  {id:'milanesa',name:'Milanesas con puré',emoji:'🍽️',time:'40 min',description:'Un plato casero que siempre funciona.',ingredients:['carne','huevo','pan rallado','papa'],steps:['Pasá la carne por huevo y pan rallado.','Cociná al horno o en sartén.','Herví y pisá las papas para el puré.']},
  {id:'revuelto',name:'Revuelto de verduras',emoji:'🥘',time:'15 min',description:'Una forma práctica de usar lo que queda.',ingredients:['huevo','cebolla','zapallito'],steps:['Cortá y salteá las verduras.','Agregá los huevos batidos.','Revolvé hasta que estén cocidos.']},
  {id:'lentejas',name:'Guiso de lentejas',emoji:'🍲',time:'45 min',description:'Calentito, económico y abundante.',ingredients:['lentejas','cebolla','zanahoria','tomate'],steps:['Cociná las lentejas hasta que estén tiernas.','Rehogá las verduras.','Mezclá y dejá hervir para integrar sabores.']},
  {id:'sandwich',name:'Sándwich caliente',emoji:'🥪',time:'10 min',description:'Para resolver una comida en minutos.',ingredients:['pan','queso','tomate'],steps:['Armá el sándwich con queso y tomate.','Tostalo en sartén o sandwichera.','Serví caliente.']},
  {id:'panqueques',name:'Panqueques',emoji:'🥞',time:'20 min',description:'Dulces o salados, según lo que tengas.',ingredients:['harina','huevo','leche'],steps:['Mezclá harina, huevo y leche sin grumos.','Cociná porciones finas en sartén de ambos lados.','Rellená a gusto.']},
  {id:'pollo',name:'Pollo al horno con papas',emoji:'🍗',time:'55 min',description:'Pocos pasos y una bandeja completa.',ingredients:['pollo','papa','cebolla'],steps:['Cortá papa y cebolla, disponelas en una fuente.','Agregá el pollo y condimentá.','Horneá hasta que el pollo esté completamente cocido.']},
];

export function normalize(value){return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
const aliases={papa:['papa','patata'],huevo:['huevo'],cebolla:['cebolla'],arroz:['arroz'],zanahoria:['zanahoria'],fideos:['fideo','pasta','tallarin','tallarines','spaghetti','espagueti'],tomate:['tomate','pure de tomate','salsa de tomate'],queso:['queso','muzzarella','mozzarella'],lechuga:['lechuga'],harina:['harina'],carne:['carne','milanesa','nalga','peceto','bife'], 'pan rallado':['pan rallado','rebozador'],zapallito:['zapallito','zucchini','calabacin'],lentejas:['lenteja'],pan:['pan','pan lactal'],leche:['leche'],pollo:['pollo','pechuga']};
export function hasIngredient(items,ingredient){const words=aliases[ingredient]||[ingredient];return items.some(item=>{const name=` ${normalize(item.name)} `;return words.some(word=>{const key=normalize(word);const variants=[key,key+'s',key+'es'];return variants.some(variant=>name.includes(` ${variant} `));});});}
export function suggestions(items){return RECIPES.map(recipe=>({...recipe,missing:recipe.ingredients.filter(ingredient=>!hasIngredient(items,ingredient))})).sort((a,b)=>a.missing.length-b.missing.length||a.name.localeCompare(b.name,'es'));}
